### ISSUE TITLE
Android: Feature Request: Move data to sd card

### ISSUE THREAD

**Issue by apg1980** [Fmstrat/ownnote#102]
please implement in the next release a sollution to move data from internal storage to external sd card. my device got only 16gb memory and my notes are currently consuming <> 350MB.

**Comment by Fmstrat** [comment]
This will also be planned for the next release. I'm having to switch backends again due to limitations in sizes with sqlite (no auto-downsize). Part of this will be to store on SD. Until then, you could install the app to the SD card vs. to internal memory (or use a move-to-SD app to do that) if you would like. I don't see any reason why the app would have problems with that.

**Comment by Fmstrat** [comment]
Completed, defaulting to SD will release in 13.

**Comment by Fmstrat** [comment]
Note: to completely clear out data stored, it may be worth "Clearing Data" on the App after installing 0.0.13.
