### ISSUE TITLE
Feature request: To-do lists support

### ISSUE THREAD

**Issue by ranzhe** [Fmstrat/ownnote#127]
It would be awesome if ownnote had support for checklists/to-do lists.
Markup layout can be, for example, the same as in Taskpaper app (which is supported by many other apps).

**Comment by Fmstrat** [comment]
Have you looked at any of the existing task apps for ownCloud yet? I've considered a fork off of this project for supporting tasks, but haven't yet evaluated what exists yet.

**Comment by marco9876** [comment]
Well i rly investigated a little bit awhile ago. And there is a Tinymce? plugin already there. Since a checkbox ist just an input field with some Javascript. 

BUT: There where some Problems in activating it within Tinymce. Pure HTML Document you can activate and deactivate. I think it is even saved.

**Comment by Fmstrat** [comment]
Well, there is this already on the enhancement list: https://github.com/Fmstrat/ownnote/issues/34

That's adding checkbox support similar to Evernote. It's not a full task management system though, and I don't think ownNote will support that in the future. After I'm done with ownNote, I actually do plan on investigating task systems for ownCloud, and if there isn't a viable option, I'll create an ownTask, too.
