### ISSUE TITLE
Android: Error after login an synchronising ownnotes for Android

### ISSUE THREAD

**Issue by Pensador** [Fmstrat/ownnote#129]
Hello,

I have imported notes from evernote via webinterface of ownnotes.
After installing ownnote for Android and Login  the app starts synchronising and end with an error screen: 
TypeError: Cannot read property 'name' of undefined

After closing the error message the notes are appearing on the android device. 
Attempts to edit a note ending with the error message:
TypeError: Cannot read property 'body' of undefined

What is the reason of this error messages?
Have you problems with imported data?

Thank you for an answer

**Comment by Fmstrat** [comment]
Hi,

A little more information will help me resolve this:

- What version of ownNote are you running on Android and on the server?
- Does the web interface still work?

I'm guessing the error is occurring when it's downloading all the note bodys. The best way for me to debug this is if you could login with the debug flag, and then provide me your logcat. Are you familiar with pulling a logcat?

If so, just login with `[DEBUG]username` instead of `username` and then `adb logcat |grep Cordo` to get the relevant entries. If you're not familiar with logcat, I can try to debug it manually, but it will take significantly longer.

Thanks!

**Comment by Fmstrat** [comment]
> There is no information in the README.md provided how to set server set to Files and Database for storage

Ahh, now I understand. Login to ownCloud as your Admin user, and go to the Admin screen where you can change settings for ownCloud. There will be an ownNote section, and you can configure ownNote there. Thanks.

**Comment by Pensador** [comment]
Im using Version ownnote 0.0.8 on server and 0.0.13 on Android.
The webinterface is still working.
I can login with [DEBUB]username, the error message appear, but I'm not able to extract the logcat file because I'm not a developer.

**Comment by Fmstrat** [comment]
No problem, we can figure it out manually. A few more questions:

- You said the second error comes up when editing, does the note display OK prior to editing, and does the error come up as soon as you hit the edit button?
- How many notes do you have, and when viewed in the web interface are any of them blank or disfigured?
- On Android, if you logout, then log back in but uncheck the box for saving notes for offline use, does the first error still occur? If not, do you get any errors when viewing any of the notes?

Thanks, hopefully we can resolve this easily.

**Comment by Fmstrat** [comment]
One more:

- Do any of your notes have a blank name or a special character of some kind in the name?

**Comment by Fmstrat** [comment]
Also, if you're willing to provide it and not concerend about your note names/groups being pasted here, the following would be extremely helpful:

1) Log into your ownCloud interface
2) Visit `https://<owncloudURL>/index.php/apps/ownnote/api/v0.2/ownnote/remoteindex`
3) Cut and paste the output here

`<owncloudURL>` should be wherever you have ownCloud installed, such as `https://host.ext/owncloud`

**Comment by dr1** [comment]
Having the same problem here. Behind a version on the server-side (it tried to force upgrade from 8.0.2 to 8.0.3 so I skipped for now)

logcat: http://0260.us/wnjdt
remoteindex: http://0260.us/qhwu5

**Comment by Pensador** [comment]
Some answers on your questions:
The second error message is not reproducible but appeared as soon as hiting the edit button.
I have imported 132 notes. The notes in webinterface are displayed correctly.
After Login with unchecked box for saving notes for offline use the error still occur.
There is no note with blank title
There are some titles with +, & or . in the name and some notes with german and portuguese characters like ä, ö, ü, ã, ç, õ.

I hope, this will help you

**Comment by Fmstrat** [comment]
@dr1 OK, I can identify the issue here since it looks like somehow during import a note is listed twice and the duplicate match is failing. I can fix this.

@Pensador If you're error is coming from the same thing as dr1, then it should fix things for you, BUT without seeing the output of the URL I've requested above ( `https://<owncloudURL>/index.php/apps/ownnote/api/v0.2/ownnote/remoteindex` ), it's near impossible for me to determine exactly what the root cause is for you for sure. The characters you mention shouldn't have any specific impact.

**Comment by Fmstrat** [comment]
Alright, I think I've got this fixed. Once it makes it through testing, this is either going to get pushed out in a quick .14 fix or will hold for a bit on v1.0. Likely a .14 so you guys can get moving with it. Watch for a milestone change in the next day or so.

**Comment by Fmstrat** [comment]
The fix implemented passed testing, but it's really just an "error handler" so that things don't crash. The true fix is actually on the server side and was just completed: https://github.com/Fmstrat/ownnote/issues/136

This will eliminate duplicate listings from ever making it to the mobile device in the first place. v1.0 is very close, so this should be rolling out soon.

**Comment by Pensador** [comment]
Yes, there are notes with the same title but within different groups.
When will you roll out the fixes?
