### ISSUE TITLE
Android: Insert Link window too big

### ISSUE THREAD

**Issue by hulmgulm** [Fmstrat/ownnote#146]
The dialog shown when selecting "Context Menu" -> "Insert Link" in note editor is not responsive and shown too big:
![screenshot_2015-05-29-20-10-57](https://cloud.githubusercontent.com/assets/12165268/7889406/ab620426-063f-11e5-81e1-d19f0da0cf3d.png)

**Comment by Fmstrat** [comment]
What version of Android and what device are you running? Thanks!

**Comment by hulmgulm** [comment]
Nexus 4 with Android 5.1.1

**Comment by Fmstrat** [comment]
Actually, I forgot to ask, what version of ownNote are you running? I could have sworn the "add link" was removed since links are now auto-converted to click-able after saving.

**Comment by hulmgulm** [comment]
0.0.13

**Comment by Fmstrat** [comment]
Ahhhh, the actual issue here is that the context menu didn't get eliminated in all cases. The context menu shouldn't exist in the mobile version because it conflicts with cut/paste. From here out, to insert a link, just type the URL, and in the display once you exit out of editing will convert it to an active link.

**Comment by Fmstrat** [comment]
Removed context menu on all devices for next version.
