### ISSUE TITLE
[feature request] Add IMAP support

### ISSUE THREAD

**Issue by stefarossi** [Fmstrat/ownnote#156]
Hello,

I use OS X as my main operating system. Since version 10.5, OS X shipped with a note-taking application which syncs via IMAP, storing all the notes as HTML emails in the "Notes" IMAP folder. iOS devices use the same technique, if I remember correctly.

If IMAP support could be added to ownNote (maybe by letting the server administrator choose between saving to the filesystem or to its users' IMAP folders), it could allow Apple users to sync their native applications to ownNote.

Do you think that would be possible?

Thank you for your time!

**Comment by Fmstrat** [comment]
Unfortunately this is outside the realm of what ownNote can do since it's a lot of interaction between the DB and an IMAP server, and would be too much overhead for an on-demand system like ownCloud. Plus, there's no real way to ensure the formatting between the OSX note app and ownNote will be consistent. There will be a desktop app for ownNote in the future, just not there yet.
