### ISSUE TITLE
Links not working

### ISSUE THREAD

**Issue by busybit** [Fmstrat/ownnote#165]
When inserting a link, clicking on that link has no function. So links are useless.

**Comment by africanforest** [comment]
I'm seeing the same issue.

**Comment by Fmstrat** [comment]
Can I get a few more details? Is this occuring in Android or in the Web interface? Do they work in the note display screen? What about in the editor? What phones/Android versions do you run (if this problem is in Android)? What is your default browser?

**Comment by busybit** [comment]
It's in the Web Interface.
What is the "display screen"? I only have an editor. Browser is Firefox 39.0.

**Comment by africanforest** [comment]
Links are working now! (ownCloud 8.1 stable, ownnote 1.0.1). 
But still the cursor doesn't change on hover. It would be nice to have a cusor:pointer style to indicate that the underlined word or phrase is a link.

**Comment by Fmstrat** [comment]
Very odd. I didn't actually change anything related to links. If anyone with a note where the links aren't working is willing to provide me the source of the note, I can try to debug further.

**Comment by africanforest** [comment]
Just to clarify, the links do work now! 
I just wanted to note, that it would be nice, if the mouse cursor would change to "pointer" on mouseover to indicate that it's a link, not just underlined text.

**Comment by hulmgulm** [comment]
in the web version of ownNote 1.02, whenever I select a note, I get right into the editor. I've never seen a "display screen". In the editor, clicking a link does not open the link but <Ctrl>+Click does.

**Comment by africanforest** [comment]
Actually i did not even know that there is a mode to view notes without editor...? I only have seen the editor, also in previous versions for ownCloud 8.0.
As busybit already mentioned above, i would also like to know, if there is another view than the editor view, and, if so, how would the editor then be enabled to edit the note?
The screenshots in the appstore only show the editor view.

@Fmstrad: could you please make that clear?

**Comment by Fmstrat** [comment]
The view only mode is part of the Android app. The original request did not include whether the issue was occuring in the Web Interface or app, so I was asking everything I could think of. Unfortunately this is going to have to be a WONTFIX. I can't make links directly clickable or it would break in-line link editing/creation. How would you fix a typo in a long link without clicking at the end and backspacing the whole think?

There is another feature request to put a "view" mode before editing. Whenever that is implemented (as an option in settings), then direct click links would be included in that view.

Thanks.

**Comment by africanforest** [comment]
Thank you a lot for clarifying this!
With regard to the direction ownCloud is going since version 8.1, namely from a cloud application just to store files to an universal platform for many useful apps (i was dreaming of something like that for a long time), i think a powerful note app will become one of the most important app for ownCloud in the future, as a real replacement for evernote. And ownnote could definitely be that one.

For me, the most annoying behaviour of evernote is the fact that each change you make to notes is immediately saved without further notice.

This is why i think it's essential to have a view mode to read notes with an edit button to switch to edit mode. The main reason why we make notes is that we want to read them. To be able to edit them is important, but actually the secondary feature.
