### ISSUE TITLE
Server: Activation of version 1.05 fails (support new app store)

### ISSUE THREAD

**Issue by africanforest** [Fmstrat/ownnote#201]
When i try to activate ownNote - Notes Application 1.05 i get the following error message:

Archive vom Typ text/html werden nicht unterstützt
(Archives of type text/html are not supported)

(ownCloud 8.1)

**Comment by Fmstrat** [comment]
How are you downloading and extracting the archive for use in ownCloud?

**Comment by xenomjay** [comment]
I'm having exactly the same issue after a newly set up OwnCloud 8.1

**Comment by africanforest** [comment]
I'm a bit confused...

The app "ownNote - Notes Application by Fmstrat" (Apps menu item "Tool") can't be activated, but when i upload the latest version manually, rename it as suggested from "ownnote-ownNote-1.05" to "ownnote", then go to Apps, then the server says it will be updated to version 8.1 (while in fact it is already version 8.1) and rejects me to the login screen, forcing me to login again, then an update process begins - "currently updating to ownCloud 8.1" - (?) and finally, when i go to Apps, "ownNote - Notes Application by Fmstrat" still can't be updated.

When i go to App - not activated, i find "OwnNote 1.05 by Ben Curtis" in "experimental" state. Should i activate this one? Are you Ben Curtis? Or Fmstrat? Both apps have the same version, but different names...?

I think the process of updating that note app or apps should be simplified and clarified to avoid confusion with naming of apps and different update procedures. I still have no clue why some apps are totally easy to update by the click on the button "update to ..." and other apps have to be downloaded from github, unzipped, renamed, uploaded and activated. Maybe it's because they are labeled as "experimental"?
![ownnote_app_activation](https://cloud.githubusercontent.com/assets/1451511/8639989/9e0bce6c-28e8-11e5-90f5-f0b8f83b078f.jpg)
![ownnote_app](https://cloud.githubusercontent.com/assets/1451511/8639990/9e1a6a94-28e8-11e5-957b-740902082071.jpg)

**Comment by Fmstrat** [comment]
It's that way because the documentation for the new app update method wasn't publicized until a blog entry a day or so ago, so I wasn't even aware until this bug occurred (a reoccurring issue that the developers are hopefully going to focus on now). I've got to update the archive to support it, which I will do soon. 

The Fmstrat one is the one you manually installed. The Ben Curtis one is the one in the new "store." They decided to start using real names instead of developer names. "Experimental" just means that ownNote isn't pre-approved yet. I have a request in and since it's the second top rated app, it will hopefully get accepted soon.

**Comment by africanforest** [comment]
Thank's for the information! Now i understand why ownNotes appears two times in the list with different names of developers. 

I think there is a lot of room for enhancement of the "app store" of ownCloud... 

The "experimental" ownNote app could successfully be activated. 
Thank you for your work!

**Comment by Fmstrat** [comment]
The "store" version should work now.
