### ISSUE TITLE
Server: oc6 and oc7 support

### ISSUE THREAD

**Issue by mckaygerhard** [Fmstrat/ownnote#21]
please added support to oc6 due there still many deploy production of oc6 enterprise edition and comunity editions..

an employer never will update if oc6 still are supported and works great!

**Comment by Fmstrat** [comment]
OC7 should work, since that's what was out when I first developed the application. I'll reach out to ownCloud and see if they can provide me a percentage list of those still running OC6. If it's high enough, I'll add this to the list, but I will say it's going to be lower priority than getting the mobile apps out. Thanks for the feedback!

**Comment by mckaygerhard** [comment]
ok i confirmed works on oc7 but have some problems.. with buttons .. i cannot close the note created.. as i said in #22 editor does not close .. i install the editdoc crappy app and saves and close perfectly

i note that i shared the notes app.. this seems have some influence in that..

i modify the app , file backend.php line 49 see that assumed "data", also in api app change the "Note" to lowercase always and works!

seems u assumed always runs on apache! and apache made too many theath on new request, i swicht to lighty some ages ago!

**Comment by mckaygerhard** [comment]
Support for OC7 was confirme with oc 7.0.3, and the close bug of editor was banished.

Thanks.. very good app, now the app feel to users faster (but really all are doing in user side), editor has now two+one buttons one only for save, other for save and close and lasted one for close only.

Would be great the possibility to rename or configure the "Notes" directory.
