### ISSUE TITLE
editor does not close if opened any html file usin "files" and the notes folder

### ISSUE THREAD

**Issue by mckaygerhard** [Fmstrat/ownnote#22]
the editor build in on oc does not close... 

proceded as:
* goes to notes app
* make a note
* save
* now goes to files app
* click on note folder
* click to open recently created file note 
* file displays as html file
* try to close file with "x" in corner
* file does not close...

tested in oc7 that suppost to be suported

**Comment by Fmstrat** [comment]
I don't believe this is an issue with ownNote, as there is no ownNote code running when you are in the Files app. I've tested it on an OC7 and OC8 install I have and it seems to work fine for me, so my only guess is that you've got a corrupt HTML file that's confusing the Files app, or another plugin that works inside the file app that is interfering. I would post on the ownCloud mailing list for this one and list out your plugins for them, since it seems to be an issue involving the built in Files app.

**Comment by mckaygerhard** [comment]
i dont ave corrupt html file, i installed also after u commented the new editdoc app and have also some bugs but this can save and load perfectly those html files made with notes..

this are a bug and if u mant u'r app will be use in real enterprise and not in home made joke instalations, must tke interes in this error...
