### ISSUE TITLE
make android app available in "ad supported zero cost edition" and "ad-free paid edition" BOTH

### ISSUE THREAD

**Issue by zaxebo1** [Fmstrat/ownnote#225]
right now the Android app of ownnote ( https://play.google.com/store/apps/details?id=com.nowsci.ownnote&hl=en )
is available at google play for some cost. This is a huge upfront problem for my friends,colleagues etc whom I want to encourage to switch from proprietary platform to the open source platform.
Open source needs to make money, I strongly agree and for that we also need to make it more popular.

**But right now the android app is only available in paid form(which is an upfront cost)**

**My suggestion is that please make it available in two editions:
1) PRO edition = this is "no-advertisement" edition, but the app is "paid" (as you do it now)
2) Free edition = this is "advertisement supported" edition, but the app itself is "zero-cost"**

This advertisement supported edition will really boost your revenues and popularise your android app very much.

**Comment by zaxebo1** [comment]
feature wise both the Pro edition and Free edition will be same, only the difference will be that in one case - we have to pay upfront cost, in another case -we support the development by viewing advertisements. Atleast the end-user will have some choice.

**Comment by improti** [comment]
myownnotes (https://github.com/aykit/MyOwnNotes) is available via F-Droid. While I haven't got it to work yet others seem to be using it successfully. Maybe that is an alternative for you?

**Comment by Fmstrat** [comment]
@improti MyOwnNotes is for the original plain-text notes application, not for ownNote unfortunately.

For the cost of the app (less than a dollar USD) I'm not sure I agree with this barrier, especially considering the refund system that Android has in place. And to be clear, this app really makes no money. The ownCloud audience is way to small to turn any reasonable profit for a side-app, and the funds from it mainly cover off on ancillary costs for development (accounts/etc).

**Comment by improti** [comment]
Well, if you want my 2 cents ... I need it OpenSource (requirement) and want it here on GitHub (wish). I do try to contribute to projects in return. Far as I understood you do not offer that. That's a discussion beyond the shop thing - I don't mind if you sell the app to people who want to use the Google Store and to pay for apps. I simply do not have a Google store and refuse to install it (as it would require me to register with an account of Google). There are projects providing both btw. (e.g. https://github.com/siacs/Conversations), have you considered "dual-laning" here? For me it is out of question to provide my account details to a closed source app that might do whatever with the credentials. For me it was totally ok to switch to the "original plain-text notes application", though (the plain-text supports mark-down btw. which is quite cool for the quick note taking).

As we are at it: I do wonder why you start a new project instead of building on the existing one. But there might be good reasons for that, too. Do you mind telling?

**Comment by Fmstrat** [comment]
The existing project was way too basic for the needs of how ownNote would be developed. It also appeared to be built as a test-bed for apps in core. Building apps for ownCloud is very, very difficult. Huge developers like hyper2k have even bailed out because of it. The APIs constantly change, and security changes are made in core that aren't always communicated to the app developers that aren't part of the mix in Berlin. With all of that said, they are working to make thing easier for us, but it is still much easier on an independent dev who does this on the side to have full control of the application being developed.

Eventually ownNote for Android will be open source and likely on Fdroid, just like it's server counterpart, but that will come at a time after the iOS version is released and the mobile ecosystem surrounding it has solidified. I've discussed this a few times in other issue reports, and all the rational can be found in those.

**Comment by improti** [comment]
Interesting, thank you mate. I must admit I still cannot fully grasp your motivation (too basic to start with so better start from scratch?). And getting more people to work on a project should also help with the effort of changing APIs and alike. And I assume many people want a notes app, surely there are people that could help out (not only with programming, but documenting, dealing with issues, etc.), too. Concerning the server-app I assume you would have gotten write access to the notes app, though. 

Anyhow, thank you a lot for you time and efforts - especially for additionally laying things down for me here. I will look for the other issues you mentioned to maybe get a better picture. And I might well be back after the processes you described have taken place and you made the client open-source ...

**Comment by Fmstrat** [comment]
Sorry, to expand on the "too basic" comment: The base app has a number of third party clients that rely on plain-text only. Expanding the base app would have created situations where other developers would have to modify apps that hadn't changed in years, which could have caused issues for legacy users. Closing this out, but keep your eyes on Fdroid for an eventual release there. Thanks.
