### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by enoch85** [Fmstrat/ownnote#343]
We need a new maintainer for this app as @Fmstrat abandoned it.

The new maintainer should get full access and also a piece of the money that this app generates as it's a paid app in the Play store.

I suggest @ezula as a new maintainer and that @Fmstrat gives him some introduction to this app and what's needed and such. Does anyone else have any suggestions?

**Comment by Fmstrat** [comment]
I am definitely open to this (been looking for it, in fact). Forewarning, app revenue generation is extremely minimal, but if it's just maintenance, it shouldn't be a big hurdle. I just haven't had time to contribute further unfortunately.

**Comment by enoch85** [comment]
@Fmstrat Which skills (languages) are required to maintain this?

**Comment by Fmstrat** [comment]
@enoch85 Almost all of the server and mobile app are JavaScript. The server has basic PHP functionality for storing the notes in the DB and file system, along with importing from Evernote, but the rest is all handled with JQuery and the TinyMCE plugin. The mobile app is built on Cordova and all of the function names and variables are named in parallel.

The current overall status is functional but needs minor updates for Nextcloud. There is a version of the mobile app that "sort of" works for iOS but I kept running into issues with TinyMCE and scrolling and never got around to solving them. TinyMCE also has an asset pipeline conflict that people run into a lot and I had considered bagging it for  something else. Other than those updates most if the issues are one-off.

It took waaaayyyy more time than I expected to get something so simple running due to unexpected incompatibilities with WYSIWYG, multiple iterations of a  schema until large notes worked in the DB, and lots of trial and error in the mobile app as it worked all the way back to Android 2. That being said, the heavy lifting there is complete for the most part.

As for the mobile app, I would also migrate that to GitHub, too.

**Comment by ezula** [comment]
@enoch85 @Fmstrat I'm not saying (yet!) that i'm willing to take over the ownership of maintaining this app but I might consider doing it. My PHP skills are limited but JavaScript and JQuery should be fine. I also have some experience working with Cordova (it's just JS) :)

**Comment by Fmstrat** [comment]
@ezula Just let me know. I honestly think most would be happy if someone kept it updated to work in the latest versions with a quick test, fixed asset pipeline, and updated Cordova every now and again. A lot of the issues are based on those or requests for enhancements.

**Comment by ThomasDaheim** [comment]
I could support on the server part (see my pull request #346 with a set of changes). Not sure about the android app.

**Comment by enoch85** [comment]
@ezula No need anymore, this repo is forked. But would be awesome if you could join there instead: https://github.com/brantje/ownnote/tree/backend_refactor
