### ISSUE TITLE
White screen, no save to folder in Nexcloud 14.0.3

### ISSUE THREAD

**Issue by Leorivasc** [Fmstrat/ownnote#355]
Hi, 
Yesterday updated to Nextcloud 14.0.3, and Ownnote could not be activated, so downloaded the last version. It could activated this time, but returned only a white screen. Noticed that the option "How would you like to store your notes?" in the settings page was set to "Database and folder". Setting up a folder there also returns a white screen.
It will only work using the "Database only" option.

Is the save-to-folder option actually working?
Thanks
Leo

**Comment by thomas2403** [comment]
This issue exists since Nextcloud 13, see #351. 
I've fixed it and created a pull request, see #354 . But nobody with write access seems to care..
It's working on the web site and the Android app works too. So, if you want to, you can use use my fork:
https://github.com/thomas2403/ownnote
But please leave it open until it gets fixed here.
