### ISSUE TITLE
Android source

### ISSUE THREAD

**Issue by srednax** [Fmstrat/ownnote#53]
Hi,

Where is the source for the android app?

**Comment by Fmstrat** [comment]
Short version: Not released, yet.

Long version:

Open source mobile app development with Android is a risky business from a security perspective. I've worked with teams that released source instantly in the past on other GitHub hosted projects, and what happened before was someone took the source, stuck a hack in it, and released it to the App store under nearly the same name. Since the original version had not yet garnered enough traffic to come up first, a number of users were pulled into the scheme.

To counteract that, I'm delaying the release of the source until such a time that ownNote has gained enough popularity in the Play Store (and iOS App Store, though there is less risk there) for that not to occur. When that time has hit, the source will be released and a version will likely be placed on F-Driod as well. But before you ask, I have no timeline or roadmap for this, however.

**Comment by srednax** [comment]
I can understand that, sad as it is.

I appreciate the changes you do, so I will continue to function as a tester 
for now.

The tiny font fix works fine, I can now read the app on my phone.

I tried using it today, and lost my notes due to the app not autosaving, 
becayse the phone slipped in my hand and moved back to the notes list. I think 
for touch device apps, autosaving is really the way to go, with no save button 
at all.

And I find the app requiring extra clicks in the menu button very often. So I 
repeat my suggestions - put buttons directly in the top par for common actions 
such as "new note", and switch to edit mode automatically when a note is 
tapped once or twice.

An additional bug: The android back button is not working inside the app - it 
should do so internally, as well as by requesting the system to go back when 
out of stack.

Kindly,
Anders


Mandag den 30. marts 2015 07:54:32 skrev Fmstrat:

**Comment by Fmstrat** [comment]
Thanks. As for your input:

Back button save notification fix is in for milestone 0.0.9 (next version): https://github.com/Fmstrat/ownnote/milestones/Android%20-%200.0.9

UX enhancement's to get rid of the extra clicks are in the works: https://github.com/Fmstrat/ownnote/issues/61 I'm debating on moving this to milestone 0.0.9 as well, it just depends on how much work it requires as I get into it, but I'd like to do that prior to the iOS version anyway.

As for back button to system, added it to the next version as well. You can follow it's progress here: https://github.com/Fmstrat/ownnote/issues/68

As a note, I don't get notifications for closed issues, so if I'm slow to feedback here, that's why. Thanks.

**Comment by caco3** [comment]
What a shame :(
The promise is almost 2 years old and there are still no sources.
