### ISSUE TITLE
Android: ReferenceError: localnote is not defined

### ISSUE THREAD

**Issue by hermanthe** [Fmstrat/ownnote#60]
Really good app. But since today every time i login i get an error:

 "An application error has occurred. Full details can be found in your logcat: 
ReferenceError: localnote is not defined"

**Comment by Fmstrat** [comment]
I'm working on converting from localStorage for saving notes to a SQLite DB because some devices have issues. Regardless, I'll get this fixed for you. I'm not positive that's the issue here, but I will increase verbosity of the logging in the next version so if the error is still there it will be more descriptive. Expect a new version tomorrow.

**Comment by hermanthe** [comment]
I got 4 notes in the account, all filled with txt

thanks!

**Comment by Fmstrat** [comment]
OK, I think I found this. It looks like it's happening when a new note was created. Fix will be in the 0.0.8 release.

**Comment by qhaz** [comment]
Hi, I am experiencing the same problem with 0.0.7
I'll await 0.0.8 . . . otherwise congratulations on a great app!

thanks

**Comment by hermanthe** [comment]
I just updated my OwnNotes-App. Its working now, no problems. Thanks!
