### ISSUE TITLE
Server: Update for  CSRF attacks, check admin section for XSS

### ISSUE THREAD

**Issue by Raydiation** [Fmstrat/ownnote#90]
You seem to use the [same controller for your webapp and your api](https://github.com/Fmstrat/ownnote/blob/master/controller/ownnoteapicontroller.php) which is fine but the permissions differ substantially: Since your API sends the credentials on each request using basic auth you can skip the csrf check. However your webinterface does not send the credentials (your user does not have to enter them on any request) because it uses cookies which requires you to do the csrf check.

You can reuse the parent controller class by simply inheriting the methods but overwriting the annotations in your child controller.

The second issue is your [html quotes method](https://github.com/Fmstrat/ownnote/blob/master/js/script.js#L70), which does not seem safe enough for me since there's a wide range of possible characters and also browser error parsing fallbacks. The preferred way to solve this is to use a templating engine like [handlebars](http://handlebarsjs.com/) which handles the escaping for you. In general avoid using html() directly

Here is also a possible XSS issue https://github.com/Fmstrat/ownnote/blob/master/templates/admin.php#L20

Some minor issues while reading through the source:
* No need to do have two lines since they are already checked if no  @PublicPage is present https://github.com/Fmstrat/ownnote/blob/master/controller/ownnoteapicontroller.php#L20 and https://github.com/Fmstrat/ownnote/blob/master/lib/setval.php#L4
* No need to json_encode here, just return it as is https://github.com/Fmstrat/ownnote/blob/master/controller/ownnoteapicontroller.php#L41
* Dont use require_once manually, you can use the class loader https://github.com/Fmstrat/ownnote/blob/master/controller/ownnoteapicontroller.php#L40
* No need to access $_POST or $_GET directly, just add $name and $group to the controller parameters https://github.com/Fmstrat/ownnote/blob/master/controller/ownnoteapicontroller.php#L73
* You should require curl to be installed to not error for the user https://github.com/Fmstrat/ownnote/blob/master/lib/backend.php#L21 heres an example https://github.com/owncloud/news/blob/master/appinfo/info.xml#L32
* Linking to a route is as easy as using OC.generateUrl('/apps/ownnote') + '/your/url' https://github.com/Fmstrat/ownnote/blob/master/js/script.js#L28
* You should use dependency injection to make your app more testable

In general please take a look at the [tutorial](https://doc.owncloud.org/server/8.0/developer_manual/app/tutorial.html) which is nearly 100% your app ;)

**Comment by Fmstrat** [comment]
I will investigate all of these. The XSS you mention in the admin page.. It seems most apps use the same input fields with onChange checking. Is this a bigger issue than just ownNote?

**Comment by Raydiation** [comment]
You should by default always escape your parameters. Most apps have a terrible quality, even core apps, so you shouldn't copy too much.

**Comment by Fmstrat** [comment]
Hi,

I'm about to start working my way through this, there's a wealth of information here. I'm going to move the Handlebars idea to a separate ticket so I can handle the more security/optimization focused issues first. I'll likely take that on when I do translations since I'll be focusing on the same code. As you can likely tell, this is one of my first OC apps.

One other question. When you mention using the class loader instead of require_once, can you provide an example? Thanks!

Ben

**Comment by Raydiation** [comment]
https://doc.owncloud.org/server/8.0/developer_manual/app/classloader.html

**Comment by Raydiation** [comment]
Basically you can just add a namespace that matches the folder and file structure and the file will be automatically required if needed

**Comment by Fmstrat** [comment]
Great, thanks.

**Comment by Fmstrat** [comment]
> No need to access $_POST or $_GET directly, just add $name and $group to the controller parameters https://github.com/Fmstrat/ownnote/blob/master/controller/ownnoteapicontroller.php#L73

Apologies for the questions, but I'm taking advantage of the fact that you know OC very well. I tried updating functions to remove $_GET and $_POST, but then they fail. For instance, if I change my edit function to just:

        public function edit() {
                return $name;
        }

Then this shows up in the error log:

    "Undefined variable: name at \/opt\/groupware\/owncloud\/ownnote\/controller\/ownnoteapicontroller.php#97"

If I try to redefine the constructor to include name/group in application.php (which doesn't exist in the tutorial) it also fails. So I'm a little lost on how OC handles this part.

> No need to json_encode here, just return it as is https://github.com/Fmstrat/ownnote/blob/master/controller/ownnoteapicontroller.php#L41 

I use the json response in the Android app, so for simplicities sake I'll keep this consistent. the jQuery parseJSON function runs very quickly in timed tests, so I'm not as concerned here unless you have any specific reasons beyond that.

> No need to do have two lines since they are already checked if no @PublicPage is present https://github.com/Fmstrat/ownnote/blob/master/controller/ownnoteapicontroller.php#L20 and https://github.com/Fmstrat/ownnote/blob/master/lib/setval.php#L4

I just want to be absolutely sure before I remove this since it could cause a security issue. I don't need to have checkLoggedIn here since apps don't default to allowing public pages? What if a user went direct to the URL? This is something I've done in my shorten app, and all I had to do was not include that line to make it public.

Thanks for all your help. It's always good to receive feedback from a developer experienced with the parent app.

> Here is also a possible XSS issue https://github.com/Fmstrat/ownnote/blob/master/templates/admin.php#L20

From an "escaping" standpoint, the DB is using the standard OC PDO entries, so I'm thinking getting rid of the `echo` and replacing with OC's `p()` function would work, right? See: https://github.com/Fmstrat/ownnote/blob/master/templates/admin.php#L20

**Comment by Raydiation** [comment]
ad 1) try

    public function edit($name) {
             return $name;
    }

ad 2) You dont set the json headers and other headers that are set for you (e.g. Content-Length which is good for performance. You could also return a JSONResponse see https://doc.owncloud.org/server/8.0/developer_manual/app/controllers.html#json Apart from that you are json_encoding this stuff twice ;)

ad 3) By default everything is maximum secure, see https://doc.owncloud.org/server/8.0/developer_manual/app/controllers.html#authentication 

As for directly calling that URL: If you wrap the stuff in a class or a function, a user wont execute anything. That's also a reason why you should use classes/functions and use the autoloader.

ad 4) yes, p() works

**Comment by Fmstrat** [comment]
Alright, outside of everything moved to other tickets due to timing, these things should be straightened out for the next release now. Thanks again for your support and help.

**Comment by unkraut** [comment]
I think this issue should be reponed. Since the oc-release 8.0.5 CORS is forced and OwnNote is unusable.
