### ISSUE TITLE
Android: App doesn`t store credentials after cleaning background tasks

### ISSUE THREAD

**Issue by AGrobelnik** [Fmstrat/ownnote#92]
When logging out the app returns to the login screen. Well, actually one expects that the app will be closed. But ok, what the heck. One has to press the home button to bring the app to the background.

When using ownNote the next time, the text fields of the login screen are prefilled with the last user credentials. Thats ok - but: When the app is in the background and one kills all background tasks all credentials are lost. That means you have to enter the URL, username and password again. This is very annoying and contradicts the idea to use this app for writing a quick note.

I regularly clean the background tasks of my android phone. So for me this software is almost worthless until this behaviour hasn't changed.

Or am I missing something?

I am using ownNote 0.0.10 and Android 4.4.2

**Comment by PenIv** [comment]
Same here. Cannot exit the app gracefully and "killing" it does not save the credentials.
A "maybe" related error led my to this page:-
Leaving the phone on the Login page produce an error when the phone goes to sleep.
Error message is "Full details can not be found in your logcat: TypeError: Cannot call method 'lastIndexOf' of undefined"
After this the credentials on the screen are gone.

**Comment by Fmstrat** [comment]
Hi, I will look into the error message to see if I can figure this out. Since this doesn't occur on any of my devices, can each of you provide me a few more details:

- What device are you using?
- Who manufactures the device?
- Are you using a custom or standard ROM?
- If custom, which ROM?

Thanks.

**Comment by Fmstrat** [comment]
Also, what app/how are you clearing background tasks?

**Comment by AGrobelnik** [comment]
Hi Fmstrat,

this problem occurs here with the following devices:
 Tablet Asus MeMo Pad Full HD10 ME302 (Android 4.3) - just tested
 Phone Acer Liquid E700, (Android 4.4.2)
  
Both devices are using their default ROM (no custom ROM)
Both devices are using their default app for clearing background tasks.

As PenIv already mentioned above this happens here as well:

Leaving the phone on the Login page produce an error when the phone goes to sleep.
Error message is "Full details can not be found in your logcat: TypeError: Cannot call method 'lastIndexOf' of undefined"

**Comment by PenIv** [comment]
My device is a Google Nexus S manufactured by Samsung.
ROM is Cyanogenmod 11.0.
To clarify;
Selecting logout in the app takes one back to the Credentials screen. Expected behavior is that the app will log out and close with the credentials saved. (This expected behavior may require a Settings option to enable changes to the login credentials) Pressing the back button on the credentials screen has no response. Expected behavior is that the app should now close with credentials saved. This forces one to take the app to the background with the "Home" button. From here the app is then unloaded from memory with the default android swipe action.
Appreciating your effort. Keep at it.

**Comment by Fmstrat** [comment]
Random question, but do either of you run anything that clears data for apps or clears browser cache?

**Comment by Fmstrat** [comment]
First part of this issue is related to https://github.com/Fmstrat/ownnote/issues/93

Variables were not cleared on logout. The next step is to figure out why you're getting logged out when clearing background tasks to begin with.

**Comment by Fmstrat** [comment]
I should also note that

> Selecting logout in the app takes one back to the Credentials screen. Expected behavior is that the app will log out and close with the credentials saved.

This is not how things should or will function. How they should (and now do) function is pressing "logout" clears out all data, and goes to a blank login screen. From a security perspective, logging out should not retain any credentials. If you want to stay logged in, just background the app. Fixing the underlying issue of why it's logging out when you clear background tasks should work this out properly. Thanks.

**Comment by Fmstrat** [comment]
OK, I've fixed the error coming up with suspending the device on the logon screen. But I'm not able to reproduce any other problems. That being said, I'm running the latest dev version, which has the "back button exits app" fix https://github.com/Fmstrat/ownnote/issues/68 and the "logout/login" fix https://github.com/Fmstrat/ownnote/issues/93 so that could be covering it. What I'm now wondering if I'm unclear on is what you are all doing. Are you:
- Logging in
- Logging out
- Backgrounding the app
- Killing the app (by swiping it off)
- Restarting the app, and expecting saved credentials (this will not happen)

Or are you:
- Logging in
- Backgrounding the app
- Killing the app (by swiping it off)
- Restarting the app and not staying logged in (which is what should happen)

? The second option is how the app should be used. If that's not working for you, something's up, or it may be related to the other issues that are already fixed.

**Comment by AGrobelnik** [comment]
Hi Fmstrat,

you are right. I'm doing the first action. For me it is a habit to logout when I am done with something where I am logged in.

I tried the second version and it seems to work for me. I think I have to get used to forget the logout for this app. I think that shouldn't be a big problem.

I thank you very much for your effort.

**Comment by Fmstrat** [comment]
Great, hopefully the other two issues will work out for you as it relates to this as well. Thanks!

**Comment by brewha** [comment]
I have a samsung note 3 and I can connect to owncloud v8.0 and create/edit and save/delete notes just fine.  I can also log out of the app and simply log back in however, after logging out if I kill the app in the background or shut my phone off and back on it does not remember the settings.  This is not normal behavior for any other accounts/apps that I use.  Why is this?
