### ISSUE TITLE
Android: Add setting to edit right when tapping on a note

### ISSUE THREAD

**Issue by retoter** [Fmstrat/ownnote#95]
Hi there,

I am fastidious after years of using SimpleNote.

In 10 out of 10 cases when I open a note I also want to edit it. How about you? Hence it would be nice to drop this useless step (tab "edit").

In 10 out of 10 cases when I leave a note (f.e. to switch to another one) I also want to save and sync it. How about you? Hence it would be very nice to drop these two steps ("save" and "sync").

Thanks for reading and considering.

**Comment by Fmstrat** [comment]
I'm not sure what version you're running, but the latest version of the app in the store already auto-saves and synchronizes when leaving a note, or swapping apps. Unfortunately auto-edit will not be enabled due to loading issues on older devices and because others like it that way since it makes the viewable area larger and keeps them from accidentally editing a note or having the keyboard pop up. Once all the base functionality is down and the iOS app is out, I'll be adding some different configuration options, and this may make the list. I will change the title to reflect that. Thanks for the feedback.

**Comment by retoter** [comment]
Dear Fmstrat

Thanks for your reply. The 0.11-release works like a charm. And I am starting to like the fact that the note is initially displayed in a reading mode. I was not really aware that I was annoyed with simplenote going straight into the edit mode activating the keyboard and hence covering one third of the screen… :-)

Have a great day!
